### ISSUE TITLE
Can't scan any result when lock screen or device sleep

### ISSUE THREAD

**Issue by tuzenvn** [NordicSemiconductor/Android-Scanner-Compat-Library#107]
onScanResult has many result when app onscreen or device is active mode. but when I pressed to lock screen button cannot result from callback.

**Comment by philips77** [comment]
Have a look at this link: https://developer.android.com/training/location/background#checklist
On Android 10+ the app needs the background location permission. Perhaps this will help? Or are you trying on an older OS version?

**Comment by philips77** [comment]
I'm closing the issue due to inactivity. Please, reopen or create a new one if my advice didn't help.
