### ISSUE TITLE
Bluetooth 5 Advertisment extensions device not scannable

### ISSUE THREAD

**Issue by trix0** [NordicSemiconductor/Android-Scanner-Compat-Library#122]
Hi, 
We have changed to Advertising type: Bluetooth 5 Advertising extension
The device does not show up in scan result.(Works in nrF connect App) 
Is this type supported by the scanner? 

Thanks,
T

**Comment by philips77** [comment]
Hi,
Yes, it's supported on Android 8+, i think. You need to call `setLegacy(false)` to make it work.

**Comment by trix0** [comment]
Device: Lenovo TB-X505L 
Android version:10(29)
This is how my startScan looks like. 

```java
List<ScanFilter> filters = new ArrayList<>();
scanSettings = new ScanSettings.Builder().setLegacy(false).setScanMode(ScanSettings.SCAN_MODE_LOW_POWER).build();
scanner.startScan(filters,scanSettings, scanCallback);
```

Any idea what I could try?

**Comment by philips77** [comment]
Try with LOW_LATENCY mode.
You may also try changing scan mode to low power in nRF Connect in Settings / Scanner, and check if it doesn't work as well.

**Comment by trix0** [comment]
Works on 
Device: Pixel 4
Android version:12

Device: Samsung S10+
Android version:12


Does not work on:
Device: Lenovo TB-X505L
Android version:10

Device: Samsung Tab A 10.1 SM-T510
Android version:10

I have tried all the different settings in the ble scanner. Could not get it to work.

**Comment by philips77** [comment]
Hi,
Support for Advertising Extension in Bluetooth 5 is an optional feature and not all phones support it. You may check the flags in `BluetoothAdapter` class, or check Device Information in nRF Connect for Mobile.
