### ISSUE TITLE
Android 12 cannot scan out beacon devices

### ISSUE THREAD

**Issue by hjjice** [NordicSemiconductor/Android-Scanner-Compat-Library#132]
Android 12 cannot scan out the beacon device, using the dependent library version 1.6.0

**Comment by philips77** [comment]
Hi,
It should scan without problems.

1. Check if you see them in nRF Connect for Android.
2. Check if a different phone can scan them.
3. Check if your app has `BLUETOOTH_SCAN` permission (Nearby permission), granted in runtime.
4. Check if Location is enabled.

**Comment by philips77** [comment]
On Android 12 in your app you may also request `BLUETOOTH_SCAN` permission with `never_for_location` flag, and then no location needed.
