### ISSUE TITLE
(Long Range (Bluetooth 5.2)) LE Coded PHY

### ISSUE THREAD

**Issue by orhangulcan** [NordicSemiconductor/Android-Scanner-Compat-Library#133]
Hi, 

I am making an android application that receives the advertises and the data (hex) in it using Bluetooth LE (5.2) Long Range (LE Coded). I can see LE Coded broadcasts using the nRF Connect application, but I cannot see them when I scan using this library in my own application. Do I need to add something to a ScanSettings to get the LE Coded Phys if I'm using the right library? or Android-BLE-Library should I use this library?

My phone is Samsung Galaxy S22 Ultra 5G, as far as I can see from its documentation, it uses a 5.2 supported chip.

```
            val settings: ScanSettings =
                ScanSettings.Builder()
                    .setScanMode(ScanSettings.SCAN_MODE_BALANCED)
                    .setLegacy(false)
                    .setPhy(ScanSettings.PHY_LE_ALL_SUPPORTED)
                    .setNumOfMatches(ScanSettings.MATCH_NUM_MAX_ADVERTISEMENT)
                    .setCallbackType(ScanSettings.CALLBACK_TYPE_ALL_MATCHES)
                    .setMatchMode(ScanSettings.MATCH_MODE_AGGRESSIVE)
                    .setReportDelay(1000)
                    .build()

```
nRF Connect ScreenShot:
https://i.hizliresim.com/jyf3vrm.png

**Comment by philips77** [comment]
Try changing `.setReportDelay(1000)` to `.setReportDelay(0)`.

Or, when using this library, you may also call [`.setUseHardwareBatchingIfSupported(false)`](https://github.com/NordicSemiconductor/Android-Scanner-Compat-Library/blob/9e4094195ae2ea44617eca851ad208dda8143ec6/scanner/src/main/java/no/nordicsemi/android/support/v18/scanner/ScanSettings.java#L534-L538), which will give you batches, but under the hood will scan with report delay 0.

**Comment by philips77** [comment]
If your app is relying on Coded PHY, which is supported from Android 8, you don't have to use Scanner Compat Library at all, just the native `BluetoothLeScanner`. The point of scanner compat lib is to bring the newer API to Android 4.3 and 4.4.x.

The Android BLE Library is for handling connections, not scanning. If you want to connect to that device, you may find it useful, but it has nothing to do with scanning.

**Comment by orhangulcan** [comment]
More clear now. Thanks for your answer.
