### ISSUE TITLE
Could not find no.nordicsemi.android:thingylib:2.0.0. 

### ISSUE THREAD

**Issue by asapsonter** [NordicSemiconductor/Android-Scanner-Compat-Library#140]
// nordic API
    implementation 'no.nordicsemi.android:ble:2.6.1'
    implementation 'no.nordicsemi.android.support.v18:scanner:1.6.0'
    implementation 'no.nordicsemi.android:thingylib:2.0.0'
    implementation 'no.nordicsemi.android:ble-livedata:2.6.1'

I have all this in my app level.

_ have removed  jcenter()_

**Comment by asapsonter** [comment]
But I am unable to sync   'no.nordicsemi.android:thingylib:2.0.0'

**Comment by roshanrajaratnam** [comment]
Hi what are you trying to achieve? Thingy is not available on mavenCentral as of now. You could include the project locally. Please refer to the sample [app](https://github.com/NordicSemiconductor/Android-Nordic-Thingy)
