### ISSUE TITLE
 Problem in reliability of receiving advertisements. #41 

### ISSUE THREAD

**Issue by ThomasJFR** [NordicSemiconductor/Android-Scanner-Compat-Library#15]
Hello,
I am in the process of designing an app which listens for any BLE advertisements, and filters them according to their contents. Currently, I am testing the reliability of the nordic BluetoothLeScannerCompat - that is, I am seeing if it will receive all advertisement data. I have a peripheral emitting an advertisement on channels 37-39, once every 40ms.

In nRF connect, all of these advertisements are received with great consistency, as shown in the "History" tab of any device. However, when I use the nordic (and Android Standard) Scanner, I am much less consistent in receiving these advertisements. In a 15 second timespan, my application received about 40 advertisements from the peripheral, whereas nRF Connect received about 150.

My code for the scanner:

```java
String desiredMacAddress = the peripherals mac address.
BluetoothAdapter mBTAdapter;
BluetoothLeScannerCompat mBleScanner;
ScanCallback scanCallback  = new ScanCallback (){
                @Override
                public void onScanResult(int callbackType, ScanResult result){
                    if ( result.getDevice().getAddress().equals(desiredMacAddress )
                          appendMyTextView("\n You received me!");
                    });
                }
            };

public void init(){
        final BluetoothManager btManager = (BluetoothManager) 
        scanActivity.getSystemService(Context.BLUETOOTH_SERVICE);
        mBTAdapter = btManager.getAdapter();
        mBleScanner = BluetoothLeScannerCompat.getScanner();

        scanLeDevice(true)
}

private void scanLeDevice(final boolean enable){
        if(enable) {
            new Handler().postDelayed(new Runnable() {
                @Override
                public void run() {
                    //BLEDevice Scan has ended
                   stop()
                }
            }, 15000);
            mLeScanner.startScan(scanCallback);
        }
        else{
            mScanning = false;
            mLeScanner.stopScan(scanCallback);
        }
    }

private void stop(){
     scanLeDevice(false)
}

```
Any advice on how to improve scan reliability would be much appreciated!

**Comment by philips77** [comment]
Replied here: https://github.com/NordicSemiconductor/Android-nRF-Connect/issues/41
