### ISSUE TITLE
SCAN_RESULT_TYPE_FULL

### ISSUE THREAD

**Issue by m-i-k-e-e** [NordicSemiconductor/Android-Scanner-Compat-Library#20]
Hello,

SCAN_RESULT_TYPE_FULL and SCAN_RESULT_TYPE_ABBREVIATED are private but the method setScanResultType is public.

Mike

**Comment by philips77** [comment]
This method in the native ScanSettings class uses `@SystemApi` annotation. In this lib, even thou there is the setter, the value is never used. I think it should be removed.
