### ISSUE TITLE
help, Not scanning equipment

### ISSUE THREAD

**Issue by Deepblue1996** [NordicSemiconductor/Android-Scanner-Compat-Library#23]
Android 7.0 can be scanned，Android 6.0 can not scanned the device, why?

**Comment by philips77** [comment]
Check the advertising packet. Avoid unnecessary 0s at the end

**Comment by philips77** [comment]
Also, check the location permission.

**Comment by Deepblue1996** [comment]
I have already open location permission. but i have get advertising packet is
![qq 20180731195158](https://user-images.githubusercontent.com/16926380/43458059-5fc7ada6-94fb-11e8-8e01-fb9b794b4832.png)

**Comment by Deepblue1996** [comment]
format Incorrect？

**Comment by Deepblue1996** [comment]
nRF canned scanner

**Comment by Deepblue1996** [comment]
i use your nRF test my device

**Comment by Deepblue1996** [comment]
7 and 6 Bluetooth scanning protocols are different? Will filter out my equipment？

**Comment by philips77** [comment]
I don't understand the issue. On what phone you can't see, and on what you can, in what app, what is the device, etc.

**Comment by philips77** [comment]
No, they're the same. But some cheep phone have cheep ble controllers and they have issues.

**Comment by Deepblue1996** [comment]
but android 7.0 phone Use normal, android 6.0 It's not scanned

**Comment by Deepblue1996** [comment]
Curious, the system has different requirements?

**Comment by Deepblue1996** [comment]
Already solved, error rate problem
