### ISSUE TITLE
Invoke ScanCallback in worker thread

### ISSUE THREAD

**Issue by piotr-pawlowski** [NordicSemiconductor/Android-Scanner-Compat-Library#32]
Hello,
What do you think about calling ScanCallback methods in a worker thread? It would be useful for wrapping scanner in RxJava Observable class. Right now everything is invoked in the main thread. It is simple to implement, just add a Handler param in startScan method (like in Android  SensorManager or LocationManager class).

**Comment by philips77** [comment]
How about that? Note that I made also some other changes in later commits. Added annotations etc.

**Comment by piotr-pawlowski** [comment]
Ok, it's better. But there is one more issue. Why `mHandler` is common for all callbacks? You support multiple scan callbacks, so you should wrap callback with its Handler. Right now every call `startScan` method override `mHandler` so it may casuse a memory leak and race condition.

**Comment by philips77** [comment]
How about now?

**Comment by piotr-pawlowski** [comment]
I am going to prepare PR for you, ok?

**Comment by philips77** [comment]
Btw, could you take a look at #33?

**Comment by piotr-pawlowski** [comment]
> Do you still find any issues in the latest impl?

There is still the issue with synchronization wrappers. But I gonna review whole library and prepare pull request.

**Comment by philips77** [comment]
Fixed by #34.
