### ISSUE TITLE
How to check that bluetooth device is connected or not?

### ISSUE THREAD

**Issue by IDFDeveloper** [NordicSemiconductor/Android-Scanner-Compat-Library#38]
I have using this library to scan and connect the Bluetooth devices to android app. Its working fine. Now once device is connect then i set `Connected` text in ListAdapter textview in the app that user can see that device is connected. After if any device goes to out of range or disconnected then i need to update the state `Connected` to `Connecting.....` in the ListAdapter UI but how i know that device is connected or not?
One other thing is if device is connected and its state changed (means any kind of notify ) then how to know that ? </br> Help would be very appreciate and thanks

**Comment by philips77** [comment]
Hello @IDFDeveloper,
This library can only be used to scan for Bluetooth LE devices and obtain advertising data. It does not connect to them. If you want to connect, I would recommend our other lib: https://github.com/NordicSemiconductor/Android-BLE-Library/
In the Readme file you may see how to connect to a device, how to read data, send data, etc. The API is designed to make it easy to use in a project and make the connection readable. You will get a callback whenever a device connected or disconnected, or even when changed state to connecting or disconnecting.
