### ISSUE TITLE
ScanFilter setServiceUuid doesn't work?

### ISSUE THREAD

**Issue by ZhangXinmin528** [NordicSemiconductor/Android-Scanner-Compat-Library#55]
When I use the scanner library to filter my Bluetooth LE devices ,I use the method "setServiceUuid " but doesn't work?

final String uuid = "0000fff0-0000-1000-8000-00805f9b34fb";

setServiceUuid(ParcelUuid.fromString(uuid))

**Comment by roshanrajaratnam** [comment]
Fixed in version 1.4.3.
