### ISSUE TITLE
Bonding failed

### ISSUE THREAD

**Issue by Maartinsh** [NordicSemiconductor/Android-Scanner-Compat-Library#62]
Hello,
I tested this case with Samsung S9 (Android 9.0) and Sony (Android 7.0). Same problem appears.
I also downloaded from Play Store "nRF Connect for Mobile" to make sure my implementation is not the real issue here. Same happens there.

1. I find BLE device in list
2. I do connection (everything is fine here)
3. I do "Bonding"
4. Pop-up PIN dialog appears, I enter PIN, bond is made successfully. 
5. I go to Bluetooth setting and do "unpair" on my BLE device.

then I procceed 1.-2. steps. But then, when I do "bonding" it says "bonding failed" and no PIN pop-up is shown. I tried to delete app, delete cache data on Bluetooth and restart device. At some point I made it possible to do the bonding once again. Followed the same path and then again after I unpaired device, I could not find a way to create bond with it.

My question is - is this supposed to be like that? Could it be, that my device is configurated somehow wrongly (after unpairing which is from user side, bonding data is not deleted or smth)?
I did try to refresh device cache ect., but nothing changed.

https://i.imgur.com/gzpWIau.png

**Comment by philips77** [comment]
You need to remove the bond information also on the peripheral side. Without it it may try to resume the encryption using the old keys (removed from the phone) so it will fail.
