### ISSUE TITLE
auto-stop scanning when BT turns off should 1) be option, 2) auto-resume when on (also optional)

### ISSUE THREAD

**Issue by paulpv** [NordicSemiconductor/Android-Scanner-Compat-Library#64]
Commit 8a20607d22f78e57700bf0b1fe911287d571c0ef is nice, but I think will break my app.
My app already detects BT on/off and "pauses" or "resumes" scanning as necessary.
If Android-Scanner-Compat-Library automatically stops scanning then my app could see that has a hard stop and hard stop itself.

I haven't yet updated my dependency to confirm if you change breaks my app.
But, hear me out and please let me know if my opinion seems valid...

Again, nice change, but if you are going to automatically stop scanning then coolio, but that is only part of the story.
To make this a complete solution then you must also then detect when BT is turned on and automatically start scanning if the user of your library hasn't called stop.

Also, this auto-stop/start feature should be an option, which would be fine to default to on.

It is possible that this change doesn't break my code, but I think this library would benefit from a more complete solution.

**Comment by philips77** [comment]
Hello,
Again, sorry for very long delay. 
When the Bluetooth is turned off, the state of the scanner becomes indeterministic. Logic suggests it gets stopped, so this library just makes it more clear. When Bluetooth gets enabled again it is in the app's responsibility to enable scan again if needed.
