### ISSUE TITLE
BondedDevices can not be found by sacnner

### ISSUE THREAD

**Issue by artemiseven** [NordicSemiconductor/Android-Scanner-Compat-Library#71]
if target ble device already bonded in system setting ,
than call scanner.startScan() , we can not get result in
onScanResult or onBatchScanResults.

**Comment by philips77** [comment]
Bonded devices very often advertise directly, with an empty advertising packet. The phone already knows the MAC address and knows what's in the device. Also, some phones don't report direct advertisements to the apps.
Check out of you see your device in nRF Connect.
