### ISSUE TITLE
 Scanner is not Working

### ISSUE THREAD

**Issue by samsu007** [NordicSemiconductor/Android-Scanner-Compat-Library#80]
```java
	BluetoothLeScannerCompat scanner = BluetoothLeScannerCompat.getScanner();
	ScanSettings settings = new ScanSettings.Builder()
				.setLegacy(false)
				.setScanMode(ScanSettings.SCAN_MODE_LOW_LATENCY)
				.setReportDelay(1000)
				.setUseHardwareBatchingIfSupported(true)
				.build();
	List<ScanFilter> filters = new ArrayList<>();
	filters.add(new ScanFilter.Builder().setServiceUuid(mUuid).build());
	scanner.startScan(filters, settings, scanCallback);
```
How to get mac address of BLE devices using this library ?

**Comment by philips77** [comment]
1. In your Android Manifest you need to have this line:
```xml
<uses-permission android:name="android.permission.ACCESS_FINE_LOCATION"/>
```
2. You also need to [request this permission in runtime](https://developer.android.com/training/permissions/requesting) and make sure it has been granted.
3. Batched scanning may not return all records, and the returned data may be truncated. First try with `setReportDelay(0)`, or `setUseHardwareBatchingIfSupported(false)` before using the offloaded batching.
4. Offloaded batching works well if the delay set is to 5 seconds or longer.
5. With batching enabled, using LOW_LATENCY mode doesn't make much sense. Either you want the results quickly, or you want to save the battery. If you just want to refresh UI every second, but you want the results as accurate as possible, leave LOW_LATENCY mode, leave delay = 1000 but change the `setUseHardwareFBatchingIfSupported` to false, so it's emulated by the lib. But then remember that it drains the battery, so don't use it for long time scanning.
6. First, try without the filters. When you get your devices, add features one by one and check if they are still reported.
