### ISSUE TITLE
ScanRecord parseFromBytes overwrites previous data in same adv packet

### ISSUE THREAD

**Issue by LebetsVI** [NordicSemiconductor/Android-Scanner-Compat-Library#86]
If manufacture specific data divided on 2 path, where first part in adv packet and second part on scan response packet, when parsing data in ScanRecord.parseFromBytes()
a string 
manufacturerData.put(manufacturerId, manufacturerDataBytes);

overwrite previous data because have same manufacturerId.

And as result we have manufacture specific data only from scan responce

**Comment by philips77** [comment]
This is how the native API would behave. This library just replicates the native behavior. 
If you need access to both records you'll have to parse the raw data on your own. They are ordered in LTV (Length (1 byte), Type (1 byte), Value (length - 1 bytes)). The Type for Manufacturer Data is 0xFF, and the Company ID is encoded in 2 first bytes of Manufacturer Data in Little Endian.
