### ISSUE TITLE
BluetoothLeScannerCompat.getScanner().startScan() onScanFailed(final int errorCode)

### ISSUE THREAD

**Issue by Lelight-Iot** [NordicSemiconductor/Android-Scanner-Compat-Library#90]
Hello, after calling `BluetoothLeScannerCompat.getScanner().startScan`, Then the `SCAN_FAILED_APPLICATION_REGISTRATION_FAILED` scan failed will be called back. Restarting the App does not work. What is the reason for this situation and how to prevent it.Looking forward to your reply

**Comment by philips77** [comment]
Related #89?

**Comment by Lelight-Iot** [comment]
I have no idea about that. It may be a system compatibility issue. This problem rarely occurs. When this happens,  restart Bluetooth and try again.I have no idea about that. It may be a system compatibility issue. This problem rarely occurs. When this happens,  restart Bluetooth and try again.
